"""
Global constants for ARK server manager
"""

# ARK Configuration
ARK_APP_ID = "2430930"

# Network defaults
DEFAULT_GAME_PORT = 7777
DEFAULT_QUERY_PORT = 27015
DEFAULT_RCON_PORT = 27020

# Security limits
MAX_INPUT_LENGTH = 256
MAX_PASSWORD_LENGTH = 128
MAX_SERVER_NAME_LENGTH = 128
MIN_PASSWORD_LENGTH = 8

# RCON protocol constants
RCON_AUTH = 3
RCON_EXECCOMMAND = 2
RCON_AUTH_RESPONSE = 2
RCON_RESPONSE_VALUE = 0